#version: '3.9'

volumes:
  redis_data:

networks:
  snappybackend:
    driver: bridge

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8300"
    volumes:
      - .:/snappybackend
    env_file: .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8300"
    container_name: snappy_api
    networks:
      - snappybackend

  redis:
    image: redis:7.4.1
    container_name: snappy_redis
    command: redis-server
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - snappybackend
    restart: always

