version: '3.9'

volumes:
  redis_data:
  postgres_data:

networks:
  snappybackend:
    driver: bridge

services:
  # --- BROKER ---
  redis:
    image: redis:7.4.1
    networks:
      - snappybackend
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # --- DATABASE ---
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: snappy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - snappybackend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  # --- APPLICATION LAYER ---
  api:
    build: .
    restart: always
    ports:
      - "8100:8300"
    volumes:
      - .:/home/snappybackend/app  # FIX THIS LINE
    env_file: .env
      # Switch to running daphne directly for a cleaner ASGI setup
    command: daphne -b 0.0.0.0 -p 8300 snappy_backend.asgi:application
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - snappybackend

  worker:
    build: .
    # CHANGE 'snappy' TO 'snappy_backend'
    command: celery -A snappy_backend worker --loglevel=info
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - snappybackend

#  beat:
#    build: .
#    # CHANGE 'snappy' TO 'snappy_backend'
#    command: celery -A snappy_backend beat --loglevel=info
#    env_file: .env
#    depends_on:
#      redis:
#        condition: service_healthy
#    networks:
#      - snappybackend


  beat:
    build: .
    # ADDED: --schedule /tmp/celerybeat-schedule
    command: celery -A snappy_backend beat --loglevel=info --schedule /tmp/celerybeat-schedule
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - snappybackend
