version: '3.9'

volumes:
  redis_data:

networks:
  snappybackend:
    driver: bridge

services:
  # --- BROKER ---
  redis:
    image: redis:7.4.1
    networks:
      - snappybackend
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # --- APPLICATION LAYER ---
  api:
    build: .
    restart: always
    ports:
      - "8100:8300"
    volumes:
      - .:/snappybackend
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8300
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - snappybackend

  worker:
    build: .
    # CHANGE 'snappy' TO 'snappy_backend'
    command: celery -A snappy_backend worker --loglevel=info
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - snappybackend

#  beat:
#    build: .
#    # CHANGE 'snappy' TO 'snappy_backend'
#    command: celery -A snappy_backend beat --loglevel=info
#    env_file: .env
#    depends_on:
#      redis:
#        condition: service_healthy
#    networks:
#      - snappybackend


  beat:
    build: .
    # ADDED: --schedule /tmp/celerybeat-schedule
    command: celery -A snappy_backend beat --loglevel=info --schedule /tmp/celerybeat-schedule
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - snappybackend
