name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  ECR_REPOSITORY: jyoti-duwal-q3-goal/snappy_api
  ECS_CLUSTER: jyoti-test-cluster
  API_SERVICE: snappy-api-service
  WORKER_SERVICE: snappy-worker-service
  API_TASK_DEF: .aws/api-task-def.json
  WORKER_TASK_DEF: .aws/worker-task-def.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # --- DEPLOY API ---
      - name: Fill in the new image ID and deployment metadata for API
        id: task-def-api
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.API_TASK_DEF }}
          container-name: jyoti-test-container
          image: ${{ steps.build-image.outputs.image }}
          environment-variables: |
            LAST_DEPLOYED_AT=${{ github.event.head_commit.timestamp }}
            GIT_COMMIT_SHA=${{ github.sha }}

      - name: Deploy API to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-api.outputs.task-definition }}
          service: ${{ env.API_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      # --- DEPLOY WORKER ---
      - name: Fill in the new image ID and deployment metadata for Worker
        id: task-def-worker
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.WORKER_TASK_DEF }}
          container-name: jyoti_test_worker_container
          image: ${{ steps.build-image.outputs.image }}
          environment-variables: |
            LAST_DEPLOYED_AT=${{ github.event.head_commit.timestamp }}
            GIT_COMMIT_SHA=${{ github.sha }}

      - name: Deploy Worker to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-worker.outputs.task-definition }}
          service: ${{ env.WORKER_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
