name: Deploy on Push to Main

on:
  push:
    branches:
      - main  # Trigger the workflow when there is a push to the 'main' test change 1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/snappy_backend/
            sudo git pull origin main
            sudo docker-compose up --build -d  # Build and run the containers in detached mode
          EOF
